server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.3.200
    username: leyou
    password: 123456
    virtual-host: /leyou
  redis:
    host: 192.168.3.200
ly:
  sms:
    accessKeyId: LTAIf6vJTEe70iPa
    accessKeySecret: A2ZGBWfrkz9arF908cmDWXmIrAlngA
    signName: 乐优商城
    verifyCodeTemplate: SMS_133976814