server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #限制文件上传大小
  freemarker:
    prefer-file-system-access: false
# Eureka
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
#fastdfs文件服务器配置
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  #缩略图
  thumb-image:
    width: 60
    height: 60
  #tracker地址集合
  tracker-list:
    - 119.27.169.133:22122
ly:
  upload:
    baseUrl: http://119.27.169.133/
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp
